CREATE TABLE `#__jsports_bulletins` (
	 `id` int(11) NOT NULL AUTO_INCREMENT,
	 `ownerid` int(11) NOT NULL DEFAULT 0,
	 `teamid` int(11) DEFAULT 0,
	 `bulletintype` varchar(1) DEFAULT 'B',
	 `title` varchar(50) DEFAULT 'B',	
	 `content` text DEFAULT null,
	 `startdate` date DEFAULT NULL COMMENT 'Start Date',
	 `enddate` date DEFAULT NULL COMMENT 'End Date',
	 `location` varchar(100) DEFAULT null,
	 `externalurl` varchar(100) DEFAULT null,
	 `attachment` varchar(100) DEFAULT null,
	 `createdate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	 `updatedate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	 `updatedby` varchar(25) DEFAULT null,
	 `published` tinyint(4) NOT NULL DEFAULT 0,
 PRIMARY KEY (`id`),
    KEY `bulletins_ownerid_idx` (`ownerid`, `createdate`),
    KEY `bulletins_teamid_idx` (`teamid`, `createdate`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
